# Generated by Django 5.2.3 on 2025-08-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(default='0000000000', max_length=15)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('edad', models.CharField(choices=[('mayor', 'Mayor de edad'), ('menor', 'Menor de edad')], default='mayor', max_length=10)),
                ('servicio', models.CharField(default='General', max_length=100)),
                ('primera_vez', models.BooleanField(default=False)),
            ],
        ),
    ]
